### ISSUE TITLE
Migrate the Regions Page

### ISSUE THREAD

**Issue by CatherineKiiru** [distributeaid/next-website-v2#4]
## Description
The current[ Regions page](https://distributeaid.org/regions/) needs to be migrated to the new website with NextJS, TypeScript and Tailwind. Refer to this repo to get the specs for the page https://github.com/distributeaid/distributeaid.org 

## Tasks
- [ ] Migrate the current Region page to NextJS.
- [ ] Include all recent regions that DistributeAid is currently operating in. 

### Scope

- [X] Design / Frontend (pages & components)

### Relation to DA

- [X] Contributor - I volunteer with DA or contribute to it's projects.

### Followup

- [X] Contribute content or code to help resolve this issue.
- [X] Review & test the changes to help decide if the issue is resolved.

### IP Ownership

I created the materials and own the copyright to them.

### Attestations & Copyright Assignment

- [X] To assign Distribute Aid the copyright of any materials you created specifically for this project.
- [X] That Distribute Aid has the rights to use any materials you submit which were created by you or others for general use.
- [X] That you have specified any additional licensing requirements related to the materials (crediting the original creators, licensing fees, etc).
- [X] That the materials are not also encumbered by a patent or other types of intellectual property that limit our ability to use them.

### Code of Conduct

- [X] I agree to follow Distribute Aid's Code of Conduct.

**Comment by Noimot** [comment]
I'll work on this
