### ISSUE TITLE
Migrate Homepage

### ISSUE THREAD

**Issue by CatherineKiiru** [distributeaid/next-website-v2#6]
## Description
The current website needs to be migrated to the new website with NextJS, TypeScript and Tailwind means you will maintain the design as it is. Refer to this repo to get  the specs. Note, you'll only use NextJS & Tailwind as we figure out how to use Puck on the new website. 

## Tasks
- [ ] Migrate the current homepage to NextJS. 
- [ ] Implement a data counter with the latest data on DistributeAid's milestones. The current counter (see screenshot below) is static and does not have the latest info. Check out this example for inspiration - https://codesandbox.io/p/sandbox/animated-react-js-counter-0uowr?file=%2Fsrc%2Findex.js 

##Screenshot
![Screenshot from 2024-02-21 23-07-23](https://github.com/distributeaid/next-website/assets/66266208/5f7b5306-5d75-4568-ad0d-ccc9da352c43)

### Scope

- [X] Design / Frontend (pages & components)

### Inspiration

Migrating the current website to NextJS

### Relation to DA
- [X] Contributor - I volunteer with DA or contribute to it's projects.

### Followup

- [X] Contribute content or code to help resolve this issue.
- [ ] Review & test the changes to help decide if the issue is resolved.

### IP Ownership

Others created the materials, and DA can purchase a private license to use them.

### Attestations & Copyright Assignment

- [X] To assign Distribute Aid the copyright of any materials you created specifically for this project.
- [X] That Distribute Aid has the rights to use any materials you submit which were created by you or others for general use.
- [X] That you have specified any additional licensing requirements related to the materials (crediting the original creators, licensing fees, etc).
- [X] That the materials are not also encumbered by a patent or other types of intellectual property that limit our ability to use them.

### Code of Conduct

- [X] I agree to follow Distribute Aid's Code of Conduct.

**Comment by rica213** [comment]
@CatherineKiiru I'd like to work on this.
