### ISSUE TITLE
Component: Navigation Bar

### ISSUE THREAD

**Issue by CatherineKiiru** [distributeaid/next-website-v2#88]
### Description
Create the navbar component based on the new [design](https://www.figma.com/design/Yq8LKeIVka701hYL45heud/Colors-for-DA?node-id=181-9480&m=dev). The navbar should include:

### Tasks
- [ ] Should include links to home, about us, needs, regions, resources, tech and donation pages
- [ ] Should be mobile responsive

### Good Practice
- [ ] Ensure accessibility in elements & images - [read more here](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML) on how to improve accessibility in your project
- [ ] Include type safety where necessary
- [ ] Write tests
