### ISSUE TITLE
Section: Donation Landing Section

### ISSUE THREAD

**Issue by CatherineKiiru** [distributeaid/next-website-v2#90]
### Task
Create this section using Radix UI. Include the buttons created in issue #89 in this section. [Design](https://www.figma.com/design/Yq8LKeIVka701hYL45heud/Colors-for-DA?node-id=181-9502&m=dev) 

Snapshot
![Image](https://github.com/user-attachments/assets/afe4c466-cd31-4c81-965c-0c9057c39be9)

### Good Practice
- [ ] Ensure accessibility in elements & images - [read more here](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML) on how to improve accessibility in your project
- [ ] Include type safety where necessary
- [ ] Should be mobile responsive
- [ ] Write tests
