### ISSUE TITLE
Component: Donate campaign Cards

### ISSUE THREAD

**Issue by CatherineKiiru** [distributeaid/next-website-v2#91]
### Task
Create the campaign cards in the donate section using Radix UI.  [Design](https://www.figma.com/design/Yq8LKeIVka701hYL45heud/Colors-for-DA?node-id=181-9502&m=dev) 

Snapshot
![Image](https://github.com/user-attachments/assets/8de8feb4-79c7-467d-8912-ed3273765416)

### Good Practice
- [ ] Ensure accessibility in elements & images - [read more here](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML) on how to improve accessibility in your project
- [ ] Include type safety where necessary
- [ ] Should be mobile responsive
- [ ] Write tests

**Comment by jtfairbank** [comment]
I created a component for these cards to try Radix out!  See `src/components/donate/CampaignCard.tsx`

However getting the header section and multiple cards displayed on the page still needs to be done.

**Comment by jtfairbank** [comment]
We'll also need some design direction on the "More Info" section.  I'm thinking it just links to a region / project page?

**Comment by CatherineKiiru** [comment]
I think so too, I've notified Tay on Figma to create designs for the regions/project page. I'll replicate the card across the campaign section

**Comment by jtfairbank** [comment]
@Huiclaire yes!  In general you can just self-assign any open issue that's not already assigned to someone else.  I believe that @hola-soy-milk and I did some initial work related to this, so please checkout the existing component.  You can see our work on #83

**Comment by Huiclaire** [comment]
Got it, thanks for letting me know! I’ll self-assigned and check #83 first. 😊

**Comment by hcavanaugh** [comment]
Closed, resolved in #414
